apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
    - name: k8s-demo
      image: wardviaene/k8s-demo
      ports:
        - name: nodejs-port
          containerPort: 3000
      livenessProbe:
        httpGet:
          path: /
          port: 3000
        initialDelaySeconds: 15
        timeoutSeconds: 30

